# Generated by Django 5.0.3 on 2024-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpeg', upload_to='image/%Y', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
